server:
  port: 8087
#数据库设置
spring:
  datasource:
  #mysql
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: tju1895
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
    pool:
        max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
        min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
        max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出
