server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: tju1895
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.model