server:
  port: 8087
#数据库设置
spring:
  datasource:
  #oracle vbsrac是实例
  #    url: jdbc:oracle:thin:@//10.233.12.221:1526/vbsrac
  #    username: invest
  #    password: invest
  #    driver-class-name: oracle.jdbc.OracleDriver
  #mysql
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: tju1895
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小initialSize，最小minIdle，最大maxActive
    maxActive: 50
    initialSize: 5
    minIdle: 1
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #oracle
    #    validationQuery: select 1 from dual
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    activiti:
    ####校验流程文件，默认校验resources下的processes文件夹里的流程文件 false即启动项目，不去校验processes。
      check-process-definitions: true
  jpa:
  #    database: oracle
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.model
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check