
server:
  port: 8088
  session:
    timeout: 30
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&useSSL=true
    username: root
    password: tju1895
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: mysql
      hibernate:
        ddl-auto: update
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.demo.model